apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-db
spec:
  serviceName: mongo-db
  replicas: 2
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        -
          name: mongo-db
          image: mongo
          imagePullPolicy: Always
          env:
            -
              name: MONGO_INITDB_ROOT_USERNAME
              value: use
            -
              name: MONGO_INITDB_ROOT_PASSWORD
              value: passw

          ports:
            -
              containerPort: 27017
              name: mongodb

          volumeMounts:
            -
              name: tbolbas-mongodb-persistent-storage
              mountPath: /data/db

      volumes:
        -
          name: tbolbas-mongodb-persistent-storage
          persistentVolumeClaim:
            claimName: tbolbas-mongodb-pvc
